---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.configmapname }}
  namespace: {{ .Values.namespace }}
  labels:
    project: {{ .Values.project }}
data:
  {{- range $key, $val := .Values.config}}
  {{ $key }}: {{ $val | quote }}
  {{- end}}