---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace }}
  labels:
    project: {{ .Values.project }}
    app: {{ .Values.name }}
  annotations:
    checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
spec:
  replicas: 1
  selector:
    matchLabels:
      project: {{ .Values.project }}
      app: {{ .Values.name }}
      env: {{ .Values.env }}
  template:
    metadata:
      labels:
        project: {{ .Values.project }}
        app: {{ .Values.name }}
        env: {{ .Values.env }}
    spec:
      containers:
      - name: {{ .Values.name }}
        image: {{ .Values.image.name }}
        ports:
          - containerPort: 8080
        envFrom:
        - configMapRef:
            name: {{ .Values.configmapname }}
            optional: false
        imagePullPolicy: Always
      restartPolicy: Always
      priorityClassName: {{ .Values.name }}