export const ErrorMessage = {
  notPermission: 'Access denied',
  notUser: 'User not found',
  notInvestor: 'Investor not found',
  notIssuer: 'Issuer not found',
  notActiveIssuer: 'You cannot approve a product with an inactive Issuer',
  notNotification: 'Notification not found',
  notProduct: 'Product not found',
  notCompliance: 'Compliance not found',
  notComplianceReject: 'You can not reject your own compliance',
  notReceiverId: 'ReceiverId not found',
  notHolding: 'Holding not found',
  notActiveProduct: 'Product status is not Active',
  notPossibleDeactivationInvestor: 'Deactivation is not possible because this investor still owns products',
  notPossibleDeactivationIssuer: 'Deactivation is not possible because this issuer still owns products',
  notUserDeleted: 'user not deleted',
  notProductDeactivation: 'You cannot deactivate the product because the product has transactions pending approval',
  notReturnTickets: 'You can’t return tickets as long as Product is active',
  notPossibleCreateSellTransaction: 'It`s impossible to sell the product after the full repayment',
  invalidRequest: 'Invalid request',
  invalidComplianceAction: 'Invalid compliance action name',
  invalidMaximumAvailableAmount: 'The maximum available amount is exceeded',
  invalidOriginalAmount: 'The amount exceeds the original amount',
  invalidContract: 'Contract is not deployed',
  invalidNonCallPeriod: 'Non-call period cannot be bigger than maturity',
  invalidNonCallPeriodExpired: 'Non call period has not yet expired',
  invalidTransactionType: 'Unknown type of transaction',
  invalidUserType: 'Unknown type of user',
  invalidPeriodType: 'Invalid type of period',
  complianceResolved: 'Compliance is resolved',
  productNameExists: 'Product with this name already exists',
  sellYourself: 'You can\'t sell a product to yourself',
  userPrincipalNameExist: 'User already exists',
  emailExist: 'Email is already exist',
  productPendingDeactivation: 'You cannot create a transaction for a product with a pending deactivation approval',
  isProductDeactivated: 'Product already deactivated',
  isAccountDeactivated: 'Account already deactivated',
  alreadySentWaitDecision: 'request was already sent. please wait the decision',
  wrongData: 'Wrong data',
  repaymentAmountExceeds: 'The selected investors have already been repaid',
  repaymentPendingApproval: 'You need to wait for the approval or rejection of the previous transaction Payment Type Repayment',
  isInterestTransactionQuarter: 'Transaction Payment Type Interest was made this quarter'
};